name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main
      - '*'

jobs:
  trigger-gitlab-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/setup-git@v2

      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST \
            --url "https://gitlab.example.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline" \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_CI_TOKEN }}" \
            --form "token=${{ secrets.GITLAB_CI_TRIGGER_TOKEN }}" \
            --form "ref="main"" \
            --form "variables[GH_BRANCH_NAME]=${{ github.event.ref }}"
