name: Trigger GitLab CI

on:
  push:
    branches:
      - main
  create:
    branches:
      - '*'

jobs:
  trigger-gitlab-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab CI
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            REF="main"
          elif [ "${{ github.event_name }}" = "create" ]; then
            REF="${{ github.event.ref }}"
          else
            echo "Unsupported event: ${{ github.event_name }}"
            exit 1
          fi

          curl -X POST \
           --fail \
           -F token=TOKEN \
           -F ref=REF_NAME \
           https://gitlab.com/api/v4/projects/48639908/trigger/pipeline
