name: Trigger GitLab Pipeline
on:
  push:
    branches:
      - main
      - '*'
jobs:
  trigger-gitlab-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
      
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: GitLab Pipeline Trigger
      uses: digital-blueprint/gitlab-pipeline-trigger-action@v1.0.6
      with:
        host: 'gitlab.com'
        id: '48639908'
        ref: 'main'
        trigger_token: ${{ secrets.GITLAB_CI_TRIGGER_TOKEN }}
        access_token: ${{ secrets.GITLAB_CI_TOKEN }}
        variables: '{"GH_BRANCH_NAME":"${{ steps.extract_branch.outputs.branch }}"}'
      
#    - name: Trigger GitLab Pipeline
#      run: |
#        curl --request POST \
#          --url "https://gitlab.com/api/v4/projects/48639908/trigger/pipeline" \
#          --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_CI_TOKEN }}" \
#          --form "ref=main" \
#          --form "token=${{ secrets.GITLAB_CI_TRIGGER_TOKEN }}"
#          --form "variables[GH_BRANCH_NAME]=${{ steps.extract_branch.outputs.branch }}"
