name: Trigger GitLab Pipeline
on:
  push:
    branches:
      - main
      - '*'
jobs:
  trigger-gitlab-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
      
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Trigger GitLab Pipeline
      run: |
        curl --request POST \
          --url "https://gitlab.com/api/v4/projects/48639908/trigger/pipeline" \
          --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_CI_TOKEN }}" \
          --form "ref=${{ github.event.ref }}" \
          --form "token=${{ secrets.GITLAB_CI_TRIGGER_TOKEN }}"
#          --form "variables[GH_BRANCH_NAME]=${{ steps.extract_branch.outputs.branch }}"
